### ISSUE TITLE
对比实验数据偏差大

### ISSUE THREAD

**Issue by SwimmingLiu** [JCruan519/EGE-UNet#12]
想问一下作者大大，所有的对比实验都是自己复现的代码还是开源代码？论文中U-Net训练ISIC2017数据集DSC能够达到86.99。而我使用[UNet-pytorch](https://github.com/milesial/Pytorch-UNet)只能达到83.976。这个结果差距会不会太大了一点？
![1](https://github.com/JCruan519/EGE-UNet/assets/53814462/41bf67a8-420b-4d80-abbd-bba51ecc4035)
![2](https://github.com/JCruan519/EGE-UNet/assets/53814462/e2116db5-9f5d-4ece-9f23-62b253febe60)
另外EGE-UNet在ISIC2017数据集的复现结果也略微偏低，请问这是我显卡的问题嘛？
![3](https://github.com/JCruan519/EGE-UNet/assets/53814462/044957bb-00ad-405e-af2b-e8eaea0f5fca)

**Comment by LeeChamner** [comment]
论文里写了这样一句话“we conduct 5 times and report the mean and standard deviation of the results for each dataset.”，是不是因为作者训练了5次取的平均结果。

**Comment by hz1z** [comment]
@SwimmingLiu  你unet应该用了数据增强，你如果不正则化，随机翻转，应该unet跑150epoch就是77多, 另外兄弟你还做这个方向吗，想加您qq交流一下，我的企鹅是2576642465
