### ISSUE TITLE
Can you improve the code for the test? Thank you so much！

### ISSUE THREAD

**Issue by Jacky-Android** [JCruan519/EGE-UNet#8]
When running your code today, I found that the code I wrote could not predict the desired segmentation graph.

**Comment by Nitrogen216** [comment]
You can refer to my code. [https://github.com/Nitrogen216/EGE-UNet](url)

**Comment by wzh0328** [comment]
> You can refer to my code. [https://github.com/Nitrogen216/EGE-UNet](url)

May I ask why there is no content in the page displayed by this link？

**Comment by wzh0328** [comment]
> When running your code today, I found that the code I wrote could not predict the desired segmentation graph.

Did you find the code for the test? If you find it, can you share it? My email address is 507841137@qq.com

**Comment by Zadsff** [comment]
> When running your code today, I found that the code I wrote could not predict the desired segmentation graph.

May I ask if you have found the predicted code? Can you share it?

**Comment by Zadsff** [comment]
> > When running your code today, I found that the code I wrote could not predict the desired segmentation graph.
> 
> Did you find the code for the test? If you find it, can you share it? My email address is [507841137@qq.com](mailto:507841137@qq.com)

May I ask if you have found the predicted code? Can you share it?

**Comment by wzh0328** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，您的邮箱我已收到，谢谢合作

**Comment by Jacky-Android** [comment]
complate
